### PR TITLE
Adding Last Will mechanism

### PR DESCRIPTION
**Pull request by ameykshirsagar**
Hi,
I am proposing a Last Will mechanism in this library
Usage
````
options.willTopic="/will"
options.willPayload = "Will Message"
options.willQos = 0
options.willRetain = true
````

I am not an expert but if there is anything wrong, my apologies. But let me know if there is anything wrong.
I have tested the library for its working and it is working perfectly. Although I haven't figured out how to set QoS 2 to Last Will QoS

### CODE REVIEW

**Comment by PasiSalenius** [comment]
Not going to merge this as is, since it needs some more consideration.

First, I think not all of the Last Will related option properties should be optional. It would be best that they are set to sensible default values where possible. Could the willQos and willRetain properties be set to a default and then be configurable through the options struct?

Perhaps a more sane path would be to create a new LastWillMessage struct, that has topic, retained flag, QoS and payload as properties. The lastWillMessage would be nil by default, but the user could set it to a struct if necessary. This way all the parameters would be nicely packaged together.

By the way, your use of connectFlags |= 0b00000000 is redundant, the bitwise OR operator there with 0 will do nothing :) To zero out bits you need to use bitwise AND operator i.e. &.

Setting the Will QoS to 2 should work like this
`connectFlags |= 0b00010000`

Also, for this library I think the level of commenting you have is unnecessary. Although I do admit the LightMQTT source code could benefit from having more comments than it does now.

**Comment by ameykshirsagar** [comment]
Alright. I will consider your points
But according to protocol, there no defaults for Last Will. Because when the Will Flag is set to 1, the topic, payload, QoS and retain flags should be set in sequence. If the will flag is not set as 1, the rest of the data is not at all considered by the server. Hence it makes no sense to put defaults for willRetain and willQos 
The struct way is better than current implementation for last will config. I agree. 
Regarding the comments I forgot to cleanse them. My apologies. 
This is just my first working PR so that you can test it out immediately. Any way I shall post the changes. 
Although do you think clean session needs an optional boolean?? Rather than enforcing new session

**Comment by PasiSalenius** [comment]
In the LastWillMessage struct properties other than topic and payload could still have default values, and not be optional, right?

Currently Clean Session is set to true, so that would be the default value for it.
`var connectFlags: UInt8 = 0b00000010 // clean session`

**Comment by ameykshirsagar** [comment]
The default values are just zero bits as per what I have read in the specification, which anyway are set zero if we do not set them, just as current implementation does.
I have created a struct for LastWillMessage, does this looks good??
````swift
fileprivate struct LastWillMessage{
    var topic: String
    var payload: String
    var qos: Int
    var retain: Bool
    
    init(topic: String, payload: String, qos: Int, retain: Bool) {
        self.topic = topic
        self.payload = payload
        self.qos = qos
        self.retain = retain
    }
    var connectFlags: UInt8{
        
        var flags: UInt8
        //Setting Will Flag
        flags = 0b00000100
        if retain {
            flags |= 0b00100000
        }
        switch qos{
        
        case 1://setting the Will QoS 1
            flags |= 0b00001000
        case 2 ://setting the Will QoS 2
            flags |= 0b00010000
        default://setting the Will QoS 0
            flags |= 0b00000000
        }
        return flags
    }
    var completePayload: Data{
        var bytes = Data()
        
        bytes.append(topic.data(using: .utf8)!)
        bytes.append(payload.data(using: .utf8)!)
        
        
        return bytes
    }
}

````
When I have referred to Paho library in Android, there is an an option for choosing to have a clean session, so I thought maybe we can have an extra option in `Bool` format to choose whether the session needs to be a clean session.
Plus I have made some more new changes to add an extra parameter to publish and subscribe methods for choosing QoS & adding retain flag to publish method. Should I raise a different PR for adding these features or can I put those features in this PR itself??

**Comment by PasiSalenius** [comment]
This does nothing (OR with zero), you should use &= 0b11100111 or just break there instead.
```
default: //setting the Will QoS 0
   flags |= 0b00000000
}
```

You should probably be reading from options.lastWillMessage inside func mqttConnect(), where the other connect flags are also set, instead of forming flags just for the Last Will bits.

The other extra options should be left for later PRs. And remember that adding QoS is not as simple as giving the option and setting the flag in the connect message. The client would actually know how to retransmit messages, which is not trivial in this case.

**Comment by PasiSalenius** [comment]
Closing this for now

**Pull request closed without merging**
